services:
  pyrsia:
    image: pyrsia/node
    build:
      target: node
    command: ["-p", "7888"]
    stdin_open: true
    ports:
      - "7888:7888"
    volumes:
      - "pyrsia:/tmp"

volumes:
  pyrsia:
